sudo: false

addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: ""

script:
  - mkdir build
  - cd build
  - cmake ..
  - cd ..
  - NUMBER_OF_PROCESSORS=$(nproc --all)
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/
  - sonar-scanner -Dsonar.cfamily.cache.enabled=true -Dsonar.cfamily.cache.path=${TRAVIS_HOME}/.cfamily -Dsonar.cfamily.threads=${NUMBER_OF_PROCESSORS}

cache:
  directories:
    - $HOME/.sonar/cache
    - $HOME/.cfamily